name: Trigger auto deployment for software-engineer-resume-app

on:
  # Automatically trigger on push to main
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/software-engineer-resume-app-AutoDeployTrigger-4fca62f8-ced7-4c17-ae31-73e3cdc31730.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SOFTWAREENGINEERRESUMEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SOFTWAREENGINEERRESUMEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SOFTWAREENGINEERRESUMEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry, then deploy to ACA
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: ./Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.SOFTWAREENGINEERRESUMEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SOFTWAREENGINEERRESUMEAPP_REGISTRY_PASSWORD }}
          containerAppName: software-engineer-resume-app
          resourceGroup: software-engineer-resume
          imageToBuild: cmrnsmrt/software-engineer-resume-app:${{ github.sha }}
